services:
  - type: web
    name: aditya-hackathon-2026
    runtime: python
    buildCommand: bash build.sh
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
