/**
 * featureData.js
 * Comprehensive mock data and helpers powering the 20-Feature Next-Gen Stack
 * for Arogya Setu Local (SIH26133).
 */

export const INITIAL_DOCTORS = [
  {
    id: 'DR-101',
    name: 'Dr. Rajesh Sharma',
    qualification: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    hospitalId: 'hosp-1',
    hospitalName: 'Rampur Primary Health Centre (PHC)',
    distance_km: 1.8,
    status: 'Available', // 'Available' | 'In Consultation' | 'On Emergency Round' | 'Off Duty'
    opdRoom: 'Room No. 03 (Ground Floor)',
    timing: '09:00 AM – 02:00 PM',
    experience: '12 Years (Rural Medical Service)',
    teleconsultReady: true,
    activePatientsInQueue: 4,
    phone: '+91 94250 88211',
    rating: 4.8,
  },
  {
    id: 'DR-102',
    name: 'Dr. Sunita Deshmukh',
    qualification: 'MBBS, DGO (Obstetrics & Gynecology)',
    specialty: 'Obstetrics & Gynecology (Maternal Care)',
    hospitalId: 'hosp-2',
    hospitalName: 'Gangaon Community Health Centre (CHC)',
    distance_km: 4.2,
    status: 'Available',
    opdRoom: 'MCH Wing, OPD 1',
    timing: '08:30 AM – 03:30 PM',
    experience: '9 Years',
    teleconsultReady: true,
    activePatientsInQueue: 7,
    phone: '+91 98221 44320',
    rating: 4.9,
  },
  {
    id: 'DR-103',
    name: 'Dr. Arun Patil',
    qualification: 'MBBS, MS (General Surgery, Trauma)',
    specialty: 'Emergency & Trauma Care',
    hospitalId: 'hosp-3',
    hospitalName: 'Nagpur District Sub-Divisional Hospital',
    distance_km: 8.5,
    status: 'Available',
    opdRoom: 'Emergency Trauma Ward No. 1',
    timing: '24x7 Emergency Duty',
    experience: '15 Years',
    teleconsultReady: false,
    activePatientsInQueue: 12,
    phone: '+91 71225 99012',
    rating: 4.7,
  },
  {
    id: 'DR-104',
    name: 'Dr. Priya Varma',
    qualification: 'MBBS, DCH (Pediatrics)',
    specialty: 'Pediatrics & Child Health',
    hospitalId: 'hosp-2',
    hospitalName: 'Gangaon Community Health Centre (CHC)',
    distance_km: 4.2,
    status: 'In Consultation',
    opdRoom: 'Pediatric Ward, Room 05',
    timing: '10:00 AM – 04:00 PM',
    experience: '8 Years',
    teleconsultReady: true,
    activePatientsInQueue: 5,
    phone: '+91 94231 77800',
    rating: 4.9,
  },
  {
    id: 'DR-105',
    name: 'Dr. Amitav Mukherjee',
    qualification: 'MBBS, MD (Cardiology)',
    specialty: 'Cardiology',
    hospitalId: 'hosp-3',
    hospitalName: 'Nagpur District Sub-Divisional Hospital',
    distance_km: 8.5,
    status: 'Available',
    opdRoom: 'Cardiac OPD, 2nd Floor',
    timing: '11:00 AM – 05:00 PM',
    experience: '14 Years',
    teleconsultReady: true,
    activePatientsInQueue: 9,
    phone: '+91 71228 11990',
    rating: 4.9,
  },
]

export const ESSENTIAL_MEDICINES = [
  {
    id: 'MED-01',
    name: 'Polyvalent Anti-Snake Venom (ASV)',
    category: 'Emergency & Anti-Toxins',
    dosage: '10ml Vial (Injectable)',
    stockStatus: 'In Stock', // 'In Stock' | 'Low Stock' | 'Out of Stock'
    quantity: 28,
    unit: 'vials',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 6, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 12, distance_km: 4.2 },
      { name: 'Nagpur District Hospital', qty: 45, distance_km: 8.5 },
    ],
    usage: 'Life-saving antidote for Cobra, Krait, Russell’s Viper bites',
    priceGovt: 'Free of Cost (Govt Supply)',
  },
  {
    id: 'MED-02',
    name: 'Oral Rehydration Salts (ORS) + Zinc Tablets',
    category: 'Gastrointestinal & Dehydration',
    dosage: '20.5g Powder Sachet + 20mg Zinc',
    stockStatus: 'In Stock',
    quantity: 450,
    unit: 'sachets',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 120, distance_km: 1.8 },
      { name: 'Rampur Sub-Centre', qty: 85, distance_km: 2.1 },
      { name: 'Gangaon CHC', qty: 250, distance_km: 4.2 },
    ],
    usage: 'Treatment for acute diarrhea, cholera, and severe dehydration',
    priceGovt: 'Free of Cost',
  },
  {
    id: 'MED-03',
    name: 'Amoxicillin & Clavulanate (625mg)',
    category: 'Essential Antibiotics',
    dosage: '625mg Tablets',
    stockStatus: 'In Stock',
    quantity: 320,
    unit: 'tablets',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 80, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 240, distance_km: 4.2 },
    ],
    usage: 'Bacterial respiratory infections, pneumonia, severe ear/throat infections',
    priceGovt: 'Free of Cost',
  },
  {
    id: 'MED-04',
    name: 'Metformin (500mg) + Glimepiride (1mg)',
    category: 'Chronic NCD (Diabetes)',
    dosage: '500mg/1mg Sustained Release',
    stockStatus: 'In Stock',
    quantity: 600,
    unit: 'strips',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 150, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 300, distance_km: 4.2 },
    ],
    usage: 'Type 2 Diabetes mellitus glycemic control',
    priceGovt: 'Free of Cost',
  },
  {
    id: 'MED-05',
    name: 'Amlodipine (5mg) + Telmisartan (40mg)',
    category: 'Chronic NCD (Hypertension)',
    dosage: '5mg/40mg Tablets',
    stockStatus: 'In Stock',
    quantity: 520,
    unit: 'strips',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 140, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 260, distance_km: 4.2 },
    ],
    usage: 'Essential management for High Blood Pressure and cardiac stroke prevention',
    priceGovt: 'Free of Cost',
  },
  {
    id: 'MED-06',
    name: 'Human Recombinant Regular Insulin (100 IU/ml)',
    category: 'Emergency & Endocrine',
    dosage: '10ml Cold Chain Vial',
    stockStatus: 'Low Stock',
    quantity: 4,
    unit: 'vials',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 2, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 8, distance_km: 4.2 },
      { name: 'Nagpur District Hospital', qty: 35, distance_km: 8.5 },
    ],
    usage: 'Diabetic ketoacidosis and severe uncontrolled diabetes',
    priceGovt: 'Free of Cost',
  },
  {
    id: 'MED-07',
    name: 'Oxytocin Injection IP (5 IU/ml)',
    category: 'Maternal & Delivery Emergency',
    dosage: '1ml Ampoule',
    stockStatus: 'In Stock',
    quantity: 40,
    unit: 'ampoules',
    facilitiesWithStock: [
      { name: 'Rampur PHC (24x7 Delivery)', qty: 15, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 25, distance_km: 4.2 },
    ],
    usage: 'Prevention and management of Postpartum Hemorrhage (PPH) during childbirth',
    priceGovt: 'Free of Cost',
  },
  {
    id: 'MED-08',
    name: 'Paracetamol Pediatric Suspension (120mg/5ml)',
    category: 'Child Care & Antipyretic',
    dosage: '60ml Syrup Bottle',
    stockStatus: 'In Stock',
    quantity: 180,
    unit: 'bottles',
    facilitiesWithStock: [
      { name: 'Rampur PHC', qty: 60, distance_km: 1.8 },
      { name: 'Gangaon CHC', qty: 120, distance_km: 4.2 },
    ],
    usage: 'Fever and pain relief in infants and children',
    priceGovt: 'Free of Cost',
  },
]

export const DIAGNOSTIC_TESTS = [
  {
    id: 'TEST-01',
    name: 'Complete Blood Count (CBC & Hemoglobin)',
    category: 'Pathology & Hematology',
    sample: 'Venous Blood (2ml)',
    turnaround: '25 Minutes (Automated Cell Counter)',
    availableAt: ['Rampur Primary Health Centre (PHC)', 'Gangaon Community Health Centre (CHC)', 'Nagpur District Hospital'],
    status: 'Available Today',
    importance: 'Detects severe anemia in pregnant women, infection count, and platelet levels',
    price: 'Free (Govt Facility)',
  },
  {
    id: 'TEST-02',
    name: '12-Lead Electrocardiogram (ECG)',
    category: 'Cardiology & Emergency',
    sample: 'Non-Invasive Electrode Recording',
    turnaround: '10 Minutes (Instant Digital Printout & AI Flag)',
    availableAt: ['Rampur Primary Health Centre (PHC)', 'Gangaon Community Health Centre (CHC)', 'Nagpur District Hospital'],
    status: 'Available Today',
    importance: 'Instant detection of Acute Myocardial Infarction (Heart Attack) and arrhythmias',
    price: 'Free (Govt Facility)',
  },
  {
    id: 'TEST-03',
    name: 'Rapid Malaria Antigen (Pf/Pv) & Dengue NS1 Kit',
    category: 'Infectious Disease Screening',
    sample: 'Fingerprick Capillary Blood',
    turnaround: '15 Minutes',
    availableAt: ['Rampur Primary Health Centre (PHC)', 'Rampur Sub-Centre', 'Gangaon Community Health Centre (CHC)'],
    status: 'Available Today',
    importance: 'Differentiates cerebral malaria and dengue hemorrhagic fever in fever cases',
    price: 'Free',
  },
  {
    id: 'TEST-04',
    name: 'Obstetric Ultrasound (USG Sonography)',
    category: 'Radiology & Maternal Care',
    sample: 'Abdominal Ultrasound Probe',
    turnaround: 'Same Day with Radiologist Report',
    availableAt: ['Gangaon Community Health Centre (CHC)', 'Nagpur District Hospital'],
    status: 'Available Today (Gangaon CHC - 4.2 km)',
    importance: 'Fetal growth, placenta location, amniotic fluid volume, and twin detection',
    price: 'Free under JSSK Scheme',
  },
  {
    id: 'TEST-05',
    name: 'Digital Chest X-Ray (CXR)',
    category: 'Radiology',
    sample: 'Chest Radiograph',
    turnaround: '30 Minutes',
    availableAt: ['Gangaon Community Health Centre (CHC)', 'Nagpur District Hospital'],
    status: 'Available Today',
    importance: 'Tuberculosis cavitation, pneumonia consolidation, rib fractures, and cardiomegaly',
    price: 'Free',
  },
  {
    id: 'TEST-06',
    name: 'Glycated Hemoglobin (HbA1c) & Lipid Profile',
    category: 'Biochemistry & NCD',
    sample: 'Serum Blood (3ml)',
    turnaround: '45 Minutes',
    availableAt: ['Rampur Primary Health Centre (PHC)', 'Gangaon Community Health Centre (CHC)', 'Nagpur District Hospital'],
    status: 'Available Today',
    importance: '3-month average blood glucose control and cardiovascular stroke risk',
    price: 'Free',
  },
]

export const INITIAL_REFERRALS = [
  {
    refId: 'REF-2026-8891',
    patientName: 'Savita Devi',
    age: 28,
    gender: 'Female',
    phone: '+91 98221 55601',
    village: 'Rampur Village, Ward 3',
    originFacility: 'Rampur Sub-Centre (ASHA Anita)',
    targetFacility: 'Gangaon Community Health Centre (CHC)',
    specialtyRequired: 'Obstetrics & Gynecology (Maternal Care)',
    urgency: 'Emergency',
    reasonForReferral: 'Primigravida (38 Weeks) with severe pre-eclampsia symptoms: BP 160/110 mmHg, blurring of vision, pedal edema.',
    createdAt: 'Today, 08:45 AM',
    status: 'En Route', // 'Created' | 'Accepted' | 'En Route' | 'Arrived' | 'In Consultation' | 'Closed'
    stageIndex: 2, // 0 to 5
    assignedDoctor: 'Dr. Sunita Deshmukh',
    transportMode: '108 Ambulance (Vehicle MH-31-E-1081)',
    stalledAlert: false,
    lastUpdate: 'Ambulance GPS: 1.2 km away from CHC',
    vitals: { bp: '160/110', spo2: '97%', pulse: '92', temp: '98.6°F', isPregnant: true },
  },
  {
    refId: 'REF-2026-8892',
    patientName: 'Rameshwar Yadav',
    age: 54,
    gender: 'Male',
    phone: '+91 94250 11980',
    village: 'Kisanpur Block',
    originFacility: 'Rampur Primary Health Centre (PHC)',
    targetFacility: 'Nagpur District Sub-Divisional Hospital',
    specialtyRequired: 'Cardiology & Emergency Care',
    urgency: 'Emergency',
    reasonForReferral: 'Suspected Acute Coronary Syndrome (STEMI): Crushing retrosternal chest pain radiating to left arm, ST elevation in lead V1-V4.',
    createdAt: 'Today, 09:15 AM',
    status: 'Accepted',
    stageIndex: 1,
    assignedDoctor: 'Dr. Amitav Mukherjee',
    transportMode: '108 Cardiac Ambulance',
    stalledAlert: false,
    lastUpdate: 'Dr. Mukherjee accepted referral & prepared Cardiac ICU Bed #4',
    vitals: { bp: '150/95', spo2: '91%', pulse: '104', temp: '98.4°F' },
  },
  {
    refId: 'REF-2026-8890',
    patientName: 'Kailash Meena',
    age: 42,
    gender: 'Male',
    phone: '+91 97654 33210',
    village: 'Pipariya Tola',
    originFacility: 'Rampur PHC',
    targetFacility: 'Gangaon CHC',
    specialtyRequired: 'General Medicine / Diagnostics',
    urgency: 'Moderate',
    reasonForReferral: 'Persistent high fever with chills for 5 days, suspected Vivax/Falciparum malaria with thrombocytopenia.',
    createdAt: 'Yesterday, 04:30 PM',
    status: 'In Consultation',
    stageIndex: 4,
    assignedDoctor: 'Dr. Rajesh Sharma',
    transportMode: 'Personal E-Rickshaw',
    stalledAlert: false,
    lastUpdate: 'Undergoing CBC and IV fluid rehydration in OPD Day Care',
    vitals: { bp: '115/75', spo2: '96%', pulse: '88', temp: '102.4°F' },
  },
]

export const HIGH_RISK_WATCHLIST = [
  {
    id: 'HR-01',
    patientName: 'Meenakshi Bai',
    age: 31,
    gender: 'Female',
    village: 'Rampur South Tola',
    phone: '+91 94211 77651',
    riskCategory: 'High-Risk Pregnancy (GDM + Anemia)',
    riskLevel: 'High',
    lastVisitDate: '24 Aug 2026',
    nextScheduledVisit: '01 Sep 2026',
    keyFindings: 'Hemoglobin: 7.8 g/dL (Severe Anemia), Fasting Blood Sugar: 142 mg/dL. Prescribed IV Iron Sucrose.',
    ashaWorker: 'Anita Devi (ASHA-404)',
    actionRequired: 'Ensure Iron Sucrose infusion at PHC & dietary counseling',
  },
  {
    id: 'HR-02',
    patientName: 'Gopalrao Kulkarni',
    age: 62,
    gender: 'Male',
    village: 'Rampur Main Village',
    phone: '+91 98223 90812',
    riskCategory: 'Uncontrolled Diabetes & Hypertension',
    riskLevel: 'High',
    lastVisitDate: '18 Aug 2026',
    nextScheduledVisit: '30 Aug 2026 (Overdue by 1 Day)',
    keyFindings: 'Random Blood Sugar: 310 mg/dL, BP: 170/105 mmHg. Missed routine refill.',
    ashaWorker: 'Anita Devi (ASHA-404)',
    actionRequired: 'Urgent household home visit required for blood pressure check & medicine supply',
  },
  {
    id: 'HR-03',
    patientName: 'Baby of Kavita (4 Months)',
    age: '4 Months',
    gender: 'Male',
    village: 'Gangaon Sector 2',
    phone: '+91 97650 44319',
    riskCategory: 'Missed Immunization (Pentavalent-2 & Rota-2)',
    riskLevel: 'Moderate',
    lastVisitDate: '10 Jul 2026',
    nextScheduledVisit: '02 Sep 2026',
    keyFindings: 'Weight: 4.8 kg (Slightly underweight, Yellow Grade). Missed 10-week vaccine schedule.',
    ashaWorker: 'Sunita ANM',
    actionRequired: 'Administer Pentavalent-2 vaccine and counseling on exclusive breastfeeding',
  },
]

export const MCH_PATHWAY_DATA = [
  {
    id: 'MCH-101',
    motherName: 'Sunita Yadav',
    husbandName: 'Dinesh Yadav',
    age: 24,
    phone: '+91 98221 00981',
    village: 'Rampur Village',
    lmp: '15 Jan 2026',
    edd: '22 Oct 2026',
    gestationWeeks: '32 Weeks',
    gravida: 'G2 P1 L1 A0',
    highRisk: false,
    ancVisits: [
      { visit: 'ANC 1 (First Trimester)', date: '12 Feb 2026', status: 'Completed', bp: '110/70', hb: '11.2 g/dL', usg: 'Single live fetus' },
      { visit: 'ANC 2 (Second Trimester)', date: '18 May 2026', status: 'Completed', bp: '118/76', hb: '10.8 g/dL', usg: 'Anomaly Scan Normal' },
      { visit: 'ANC 3 (Third Trimester)', date: '14 Aug 2026', status: 'Completed', bp: '120/80', hb: '10.5 g/dL', tt1: 'TT-Booster Given' },
      { visit: 'ANC 4 (Pre-Delivery Check)', date: '15 Sep 2026', status: 'Upcoming', bp: 'Pending', hb: 'Pending' },
    ],
    institutionalDeliveryPlan: 'Rampur PHC 24x7 Delivery Suite',
    transport102Arranged: true,
  },
]

export const CHRONIC_CARE_DATA = [
  {
    id: 'NCD-01',
    patientName: 'Devidas Shinde',
    age: 58,
    disease: 'Hypertension & Type-2 Diabetes',
    baselineBP: '160/95 mmHg',
    currentBP: '128/82 mmHg',
    baselineSugar: '240 mg/dL',
    currentSugar: '135 mg/dL',
    adherenceStreak: '28 Days Consistent',
    prescriptions: ['Telmisartan 40mg (1 Morning)', 'Metformin 500mg SR (1 Post-Dinner)'],
    lifestyleTips: '30 min brisk morning walk, low salt intake (<5g/day), reduce jaggery & sweets',
    logs: [
      { date: '29 Aug', bp: '128/82', sugar: '135', status: 'Optimal' },
      { date: '27 Aug', bp: '130/84', sugar: '140', status: 'Optimal' },
      { date: '25 Aug', bp: '134/86', sugar: '148', status: 'Good' },
      { date: '22 Aug', bp: '138/88', sugar: '155', status: 'Fair' },
    ],
  },
]

export const DISTRICT_ANALYTICS = {
  districtName: 'Nagpur Rural District Health Network',
  totalFacilities: 18,
  activeDoctorsToday: 42,
  bedOccupancyRate: '68%',
  totalReferralsToday: 34,
  avgAmbulanceResponseMins: 14.5,
  criticalStockOutAlerts: 0,
  overloadedFacilities: [
    { name: 'Nagpur District Hospital', load: '92%', queue: 28, alert: 'High OPD Load' },
  ],
  optimalFacilities: [
    { name: 'Rampur PHC', load: '45%', queue: 4, status: 'Fast Access (Avg 12m wait)' },
    { name: 'Gangaon CHC', load: '60%', queue: 8, status: 'Normal Flow' },
  ],
}
